### ISSUE TITLE
A question about code.

### ISSUE THREAD

**Issue by Furkan125** [ReimarPB/GrowtopiaPacketReader#3]
Hello, I was wondering something, is it possible to modify packages or create new packages like we can read packages with this code?

**Comment by ReimarPB** [comment]
The current code does not allow for modification or creation of packets.

Looking at the Frida documentation, it looks like it'd be possible to do that and in that case, I might try to add it to this functionality at some point. For now, you will have to manually edit the `growtopia.js` file if you want to modify packets.

I'm using [`Interceptor.attach()`](https://frida.re/docs/javascript-api/#interceptor) to read the packets and it seems that you can use `retval.replace()` inside the `onLeave` callback to modify the return value. I have not tested if this works.

I think you can also call the `enet_peer_send` function at any point in time to create your own packets using [`NativeFunction`](https://frida.re/docs/javascript-api/#nativefunction).

**Comment by Furkan125** [comment]
Hello, I will try to write code and send packages but how can I use enet_peer_send?

**Comment by ReimarPB** [comment]
I just realized it's probably a bit more complicated than I initially thought it would be. You'll have to find out what arguments enet_peer_send takes, find the structs that make up the data types in those arguments, fill them in with the correct data and call the function with it.

I haven't looked into how this should be done, so if you don't know yourself, I'd suggest you use a different tool for modifying packets for now.

**Comment by Furkan125** [comment]
I used enet_peer_send in c++ before, but I don't know if its usage is the same as in javascript and I couldn't find a tutorial. I think it's called enetPeerSend in javascript because notepad++ fixed it this way, but I searched both names and no results came up.

**Comment by ReimarPB** [comment]
Oh yeah, this isn't regular JavaScript. I'm using Frida which provides a specific API for communicating with (or rather intercepting) external programs like Growtopia, all of which is is documented [here](https://frida.re/docs/javascript-api/) (yeah, the documentation kind of clunky, but it's the best resource for this).

The reason Notepad++ suggested enetPeerSend, is because that's correct, it's a variable I made. I defined it in line 4. However, this isn't the actual function though, this is just a pointer. In Frida, if you want to call a function from a Windows program, you have to use [`NativeFunction`](https://frida.re/docs/javascript-api/#nativefunction) as I stated above. But since Frida doesn't know the parameter and return types of this external function, you'll have to specify them yourself.

Notice the arguments in the native function constructor:
`new NativeFunction(address, returnType, argTypes[, abi])`
- The first parameter is the address. Here you can pass the pointer, which is the `enetPeerSend` variable I created before.
- The second parameter is the return type. As stated [here](http://enet.bespin.org/group__peer.html#gaf082a0ae58d9c435bed75c7325cf7290), the return type is an int. So pass a string that says `"int"` there.
- The third parameter is an array of the types of the arguments. As specified in the Frida documentation, if one of the types is a struct, that type in itself must be an array with all its types inside. This is where you might be better than me, since I don't actually know what the structs in ENet looks like. Everything that's a primitive type must be a string with the type name, any structs must be an array with the types inside.
- The fourth parameter can probably be ignored

The returned value should then be a function you can actually call in JavaScript. Of course I haven't tested it, but I'm fairly sure that's the case. I hope this all makes sense.

**Comment by Furkan125** [comment]
I read what you told, the sections about NativeFunction in the frida documentation and a few other resources on the internet and tried a code and got an error message.

The code I tried:
var f = new NativeFunction(enetPeerSend, "str", ["str", "str"]);
f.apply(f, ["OnDialogRequest", "add_textbox|Hello World|"]);

Error:
Error: invalid type specified
     at onLeave

**Comment by ReimarPB** [comment]
That could be because of the wrong data types in the constructor.
One thing I can tell you is that it shouldn't be "str" since no strings are passed in enet_peer_send.
I'm not entirely sure, but I think it should be something along the lines of this:

```js
new NativeFunction(
    // Function pointer
    enetPeerSend,
    // Return type
    "int",
    // Arguments
    [
        // peer
        [ /* insert ENetPeer struct types here */  ],
        // channelID
        "byte",
        // packet
        [ /* insert ENetPacket struct types here */ ]
    ]
);
```

This code is not complete, I have not filled in the data types defined in each struct (since that would take a lot of time)

As for calling the function, you need to use the exact packet bytes (not just strings) and wrap it inside an ENetPacket. You also need to capture the peer that is being used, and I assume the channel ID would be 0.

**Comment by Furkan125** [comment]
Oh I get it, thanks. But what do you mean by ENetPeer or ENetPacket struct types ?

**Comment by ReimarPB** [comment]
See for example [here](https://github.com/lsalzman/enet/blob/e3ada4ed750b976833e3d54a9c1179445289bbf6/include/enet/enet.h#L263). That's the ENetPeer struct and you have to type in all the types that make it up. For any structs that are inside that struct you will have to make another array inside with the types of that struct and so on. btw things like `enet_uint32` are the same as e.g. `uint`.

**Comment by Furkan125** [comment]
So this is how it should be, right?
new NativeFunction(
     // Function pointer
     enetPeerSend,
     // Return type
     "int",
     // Arguments
     [
         // peers
         ["ENetListNode","_ENetHost","enet_uint16","enet_uint32","enet_uint8","ENetAddress", ...],
         // channelID
         "byte",
         // packet
         [ /* insert ENetPacket struct types here */ ]
     ]
);

There are lots of enet_uint32, do I have to write them all?

**Comment by ReimarPB** [comment]
Not really, strings only work for primitive types (int, uint, byte etc.). For structs like ENetListNode, you will have to replace that with an array of all the types inside ENetListNode. For enet_uint16, enet_unt32 and so on, you can keep them as strings, just remove the `enet_` part.

**Comment by Furkan125** [comment]
I think i did this time

new NativeFunction(
    // Function pointer
    enetPeerSend,
    // Return type
    "int",
    // Arguments
    [
        // peer
        ["acknowledgementList", "outgoingCommandList", "incomingCommandList", "dispatchList", "uint8", "uint16", "uint32", "size_t", "_ENetHost", "incomingReliableCommands", "incomingUnreliableCommands", "acknowlegdements", "sentReliableCommands", "sentUnreliableCommands", "outgoingCommands", "dispatchedCommands"],
        0,
        "byte",
        // packet
        ["size_t", "uint8", "uint32", "ENetPacketFreeCallback"]
    ]
);
